Repository openshift/master-dns-operator, pull requests merged in 2018-12, with the labels that each got.

#3 Apply Deployment, switch to config v1
  Gopkg.lock
  Gopkg.toml
  Makefile
  config/binding.yaml
  config/crd.yaml
  config/deployment.yaml
  config/role.yaml
  config/sa.yaml
  manifests/02_role.yaml
  pkg/apis/masterdns/v1alpha1/masterdnsoperatorconfig_types.go
  pkg/apis/masterdns/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
  pkg/operator/masterdns/operator.go
  vendor/github.com/openshift/library-go/pkg/controller/controllercmd/builder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceapply/event_helpers.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/backingresource/backing_resource_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/installer/installer_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/node/node_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/staticpod/controller/revision/deployment_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/controller.go
  vendor/github.com/openshift/library-go/pkg/operator/status/status_controller.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper.go
  vendor/github.com/openshift/library-go/pkg/proc/reaper_unsupported.go
Labels: size/XXL

#5 Add priority class to pods
  config/deployment.yaml
  manifests/05_deployment.yaml
Labels: size/XS

#8 replace tectonicClusterID tag with openshiftClusterID
  pkg/operator/masterdns/operator.go
Labels: lgtm, size/XS
